/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2b7993f1-342b-428d-931d-a47780fb5313",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eN935b3Ou",
    "aws_user_pools_web_client_id": "60sdmi6t84lj6rnfnjllm1njb6",
    "oauth": {}
};


export default awsmobile;
